### ISSUE TITLE
Adding percentage gain/loss in Discord notification

### ISSUE THREAD

**Issue by austinyearlykim** [major/thetagang-notifications#1318]
![image](https://github.com/major/thetagang-notifications/assets/8455947/d76b5146-d8cd-480a-9c20-28aedd2ec719)

Consider adding percentage gain/loss next to dollar amount for Discord notifications.

Items to consider:
1. Rounding to to whole number? 7%? or 7.1%? or 7.11%?

**Comment by major** [comment]
I'm thinking one decimal would be enough, but also be easy to change if we need more later. :+1:
